# The function: bibtex_2academic

bibtex_2academic <- function(bibfile,
                             outfold,
                             abstract = TRUE,
                             overwrite = FALSE) {
  
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(RefManageR, dplyr, stringr, anytime, tidyr, stringi)
  
  options(encoding="UTF-8")
  # avoid umlaut probelms -----
    uml_repl <- function(x) {
      stringi::stri_replace_all_fixed(
        x, 
        c("â€™","Ã¤","Ã¶","Ã¼","â›”","Â©","â€“","Ãœ"), 
        c( "'", "ä", "ö", "ü",   "",  "©", "-" ,"Ü"), 
        vectorize_all = FALSE
      )
    }
  
  
  # Import the bibtex file and convert to data.frame- ------
  mypubs_o <- ReadBib(bibfile, check = "warn", .Encoding = "UTF-8")
  
  mypubs <- mypubs_o %>%
    as_tibble() %>%
    mutate(across(everything(),~uml_repl(.x)),
           across(everything(),~stringr::str_squish(.x)),
           rnames = mypubs_o %>% as.data.frame() %>% rownames() )
  
  
  mypubs <- mypubs  %>% 
    mutate(mainref = journal)
  mypubs$mainref <- mypubs$mainref %>% replace_na('') #otherwise it appears "NA" in post
  
  mypubs$abstract <- mypubs$abstract %>% replace_na('(Abstract not available)') #otherwise it appears "NA" in post
  #  mypubs$annotation <- mypubs$annotation %>% replace_na('image_preview = ""') #otherwise
  # Customize Zotero extra field (here "annotation") in order to leave there the additional information for the md file
  
  #clean backslashes generated by conversion of underline characters in links (_)
  # mypubs$annotation<- gsub(
  #   pattern = ('\\\\'),
  #   replacement = '',
  #   x = mypubs$annotation
  # )
  
  mypubs$abstract<- gsub(
    pattern = ('\\\\'),
    replacement = '',
    x = mypubs$abstract
  )
  
  mypubs$mainref<- gsub(
    pattern = ('\\\\'),
    replacement = '',
    x = mypubs$mainref
  )
  
  # Customize for more than one editor
  
  mypubs$editor<- gsub(
    pattern = (' and '),
    replacement = ', ',
    x = mypubs$editor
  )
  
  mypubs$editor<- stri_replace_last_fixed(mypubs$editor, ',', ' &')
  
  
  
  
  # add characters between tags for properly render
  mypubs$keywords<- gsub(
    pattern = (','),
    replacement = '","',
    x = mypubs$keywords
  )
  
  #add line breaks for the different entries
  # mypubs$annotation<-cat(stri_wrap(mypubs$annotation, whitespace_only = TRUE))
  
  # assign "categories" to the different types of publications
  mypubs   <- mypubs %>%
    dplyr::mutate(
      pubtype = dplyr::case_when(bibtype == "Article" ~ "2",
                                 bibtype == "Article in Press" ~ "2",
                                 bibtype == "InProceedings" ~ "1",
                                 bibtype == "Proceedings" ~ "1",
                                 bibtype == "Conference" ~ "1",
                                 bibtype == "Conference Paper" ~ "1",
                                 bibtype == "MastersThesis" ~ "3",
                                 bibtype == "PhdThesis" ~ "3",
                                 bibtype == "Manual" ~ "4",
                                 bibtype == "TechReport" ~ "4",
                                 bibtype == "Book" ~ "5",
                                 bibtype == "InCollection" ~ "6",
                                 bibtype == "InBook" ~ "6",
                                 bibtype == "Misc" ~ "0",
                                 TRUE ~ "0"))
  #   ex <- mypubs[6,]
  
  # create a function which populates the md template based on the info
  # about a publication
  create_rmd <- function(ex) {
    
    # create directory & file name from date and title (first 3 words)
    if (is.na(ex[["year"]]))  ex[["year"]] <- format(Sys.Date(), '%Y') # replace missing date with current year
    
    pub_name <- paste(
                    ex[["year"]],
                    ex[["title"]] %>% stringr::word(.,start = 1,end = 3) %>% # first 3 words of title
                      str_remove_all(.,pattern = "[:punct:]") %>% 
                      toupper(.) %>% 
                      gsub(.,pattern = "\\s",replacement = "_"),
                  sep = "_") %>% 
    stringi::stri_replace_all_fixed(
      ., 
      c("ä", "ö", "ü", "Ä", "Ö", "Ü"), 
      c("ae", "oe", "ue", "Ae", "Oe", "Ue"), 
      vectorize_all = FALSE
    )
    
    # full file name     
    # filename <- here::here(out_fold,pub_name,paste0(pub_name, ".md"))
    filename <- here::here(out_fold,pub_name,"index.Rmarkdown")
    
    # directory 
    if (dir.exists( here::here(out_fold,pub_name) ) == F) {
      dir.create( here::here(out_fold,pub_name) )
    }
  
    # export in md File ------
    if (!file.exists(filename) | overwrite) {
      fileConn <-  filename
      write("---", fileConn)
      
      # # Abstract
      # write(paste0("abstract: \"", ex[["abstract"]], "\""), fileConn, append = T)
      # 
      # Authors-----
        # collapse into single string
      auth_hugo <- str_split(ex["author"], " and ") %>% 
        unlist(.) %>% 
        paste0(.,collapse = ", ")
        # str_replace_all(., "Andreas Filser", "admin") %>% 
      write(paste0("author: \"",auth_hugo,"\""), fileConn, append = T)
      
      # Title -----
      ex[["title"]] <- gsub(ex[["title"]],pattern = "'",replacement =  "''")
      write(paste0("title: \'", ex[["title"]],"\'"), fileConn, append = T)
      
      # Date ----
      date_hugo <- anydate(paste0(ex[["year"]],ex[["month"]],"15",collapse = "-")) 
      write(paste0("date: ",        "\'", date_hugo, "\'" ), fileConn, append = T)
      write(paste0("publishDate: ", "\'", date_hugo, "\'" ), fileConn, append = T)
      
      # Publication type. -------
        # 0 = Uncategorized, 1 = Conference paper, 2 = Journal article
        # 3 = Manuscript, 4 = Report, 5 = Book,  6 = Book section
      write("publication_types: ", fileConn, append = T)
      write(paste0("- \"",ex[["pubtype"]],"\""),fileConn, append = T)
      
      
        if (exists('ex[["note"]]')) {
          note_url <- ( grepl("osf", ex[["note"]]) & grepl("https", ex[["note"]])  )
        } else {
          note_url <- F
        }
        
      #  links
      if (!is.na(ex[["doi"]]) | !is.na(ex[["url"]]) | note_url  ) {
        write("links:", fileConn, append = T)
      }
        
        
      # pdf link -----
      if (!is.na(ex[["url"]])){
        write(" - icon: file-pdf", fileConn, append = T)
        write("   icon_pack: fas", fileConn, append = T)
        write("   name: PDF", fileConn, append = T)
        write(paste0("   url:  \'", ex[["url"]],"\'"), fileConn, append = T)
      }  
      
      # doi -----
      if (!is.na(ex[["doi"]])){
        write(" - icon: doi", fileConn, append = T)
        write("   icon_pack: ai", fileConn, append = T)
        write("   name: Publication", fileConn, append = T)
        write(paste0("   url:  \'https://doi.org/", ex[["doi"]],"\'"), fileConn, append = T)
      }  
      
      
      # Code / Replication repo -> saved as note in zotero -----
      if ( note_url ) {
        url_pattern <- "http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+"
        code_url <- str_extract(ex[["note"]],url_pattern)
        write(" - icon: osf", fileConn, append = T)
        write("   icon_pack: ai", fileConn, append = T)
        write("   name: Code", fileConn, append = T)
        write(paste0("   url: ", code_url), fileConn, append = T)
      }  
      
      # tags ----
      tags_hugo <- 
          str_split(ex[["keywords"]], "\\,") %>% 
            unlist(.) %>% 
            str_remove_all(.,pattern = "[:punct:]") %>% 
            str_to_title(.) %>% 
            paste0("- ",.)
      if (!is.na(ex[["keywords"]]))   write(c("","tags:",tags_hugo), fileConn, append = T,  sep = "\n")
      
      
      # Publication details -----------
        # add Editor, Booktitle etc. if applicable
        ## Journal Article: Use Journal Name -----
        if (!is.na(ex[["journal"]])) {
          publication <-  paste0("publication: \'*", ex[["journal"]],"*") # Journal italic
          
          if (!is.na(ex[["volume"]]))     publication <- paste0(publication," ",
                                                                ex[["volume"]])
          if (!is.na(ex[["number"]]))     publication <- paste0(publication,"(",
                                                                 ex[["number"]], ")")
          
          if (grepl("-",ex[["pages"]]))     publication <- paste0(publication,", ",
                                                                ex[["pages"]])
          
          publication <-  paste0(publication,"\'") # close quote
          
        }
      
        ## Book chapter ------
      if (!is.na(ex[["booktitle"]])) {
        if (!is.na(ex[["editor"]]))    publication <- paste0("publication: \'In ", 
                                                             ex[["editor"]], ": ")
        if (!is.na(ex[["booktitle"]])) publication <-  paste0(publication, 
                                                              "*", ex[["booktitle"]],"*.") # Book title italic
        if (!is.na(ex[["pages"]]))     publication <- paste0(publication,
                                                             " (pp.", ex[["pages"]], ").")
        if (!is.na(ex[["publisher"]])) publication <- paste0(publication,
                                                             " ", ex[["publisher"]],"\'")
      }
      
      write(publication, fileConn, append = T)
      
      
      # Excerpt ----
      # to display authors and journal details in publication list
      publication_excerpt <- str_remove_all(publication,"publication\\:|\\*|\\'")
      
      excerp <- paste0("excerpt: \"",auth_hugo,"<br>", publication_excerpt,"\"")
      write(excerp, fileConn, append = T)
      
      
      # Subtitle -----
        # to highlight journal etc on publication page 
      pu_subtitle <- paste0(auth_hugo," ", publication_excerpt)
      write(paste0("subtitle: \'", pu_subtitle,"\'"), fileConn, append = T)
       
      # generate further fields (empty) ------
      # other possible fields are kept empty. They can be customized later by
      # editing the created md
      
      # write("url_code: ", fileConn, append = T)
      write("image_preview: ", fileConn, append = T)
      write("selected: false", fileConn, append = T)
      write("projects: []", fileConn, append = T)

      #links
      write("url_preprint: \"\"", fileConn, append = T)
      write("url_dataset: ", fileConn, append = T)
      write("url_project: ", fileConn, append = T)
      write("url_slides: ", fileConn, append = T)
      write("url_video: ", fileConn, append = T)
      write("url_poster: ", fileConn, append = T)

      #other stuff
      write("math: true", fileConn, append = T)
      write("highlight: true", fileConn, append = T)
      # Featured image
      # write("[header]", fileConn, append = T)
      # write("image: ", fileConn, append = T)
      # write("caption: ", fileConn, append = T)

      write("---", fileConn, append = T) # end YAML
      
      write("#### Abstract", fileConn, append = T) # Abstract header
      write(ex[["abstract"]], fileConn, append = T) # Abstract header
      
      
      write(" ", fileConn, append = T) # add space
      write("**[Back to publication list](/publication)**", fileConn, append = T) # add back link
      
      
      
      # export bibtex-file for citation ----
      # as.data.frame(t(dfx[,10]))
      ex_df <- data.frame(ex) # %>% 
        # select(-matches("abstract|file|rnames|note|url|copyright|langid")) %>% data.frame(.)
      
      # rownames(ex_df) <- ex[["rnames"]]
      print(ex[["rnames"]])
      RefManageR::WriteBib(bib =  RefManageR::as.BibEntry(ex_df),
                           file =  here::here(out_fold,pub_name,paste0("cite.bib")) )
      
    }
  }
  # apply the "create_md" function over the publications list to generate
  # the different "md" files.
  
  apply(mypubs, FUN = function(x) create_rmd(x), MARGIN = 1)
  
  
  # create_md()
  
}

# Run the function

my_bibfile <- "content/publication/eigene.bib"
out_fold   <- "content/publication"
bibfile  = my_bibfile;outfold   = out_fold;abstract  = TRUE;overwrite = F

bibtex_2academic(bibfile  = my_bibfile,
                 outfold   = out_fold,
                 abstract  = TRUE,
                 overwrite = F)
